[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/src-d/lookout"
  revision = "14a12e3fb0b2819d5b4145ea9ca039b1da106466"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[constraint]]
  name = "gopkg.in/src-d/go-log.v1"
  version = "1.0.1"

[prune]
  go-tests = true
  unused-packages = true
